# Generated by Django 3.2.6 on 2021-09-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',), 'verbose_name_plural': 'products'},
        ),
    ]
